name: Setup
description: Setup Node/pnpm and restore build cache

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - name: Restore build
      uses: actions/cache/restore@v4
      with:
        path: |
          node_modules
          packages/*/node_modules
          packages/*/dist
        key: build-${{ github.sha }}
